<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $currencies = [
            ["code" => "AED", "name" => "United Arab Emirates Dirham", "symbol" => "د.إ"],
            ["code" => "AMD", "name" => "Armenian Dram", "symbol" => "֏"],
            ["code" => "AOA", "name" => "Angolan Kwanza", "symbol" => "Kz"],
            ["code" => "ARS", "name" => "Argentine Peso", "symbol" => "$"],
            ["code" => "AUD", "name" => "Australian Dollar", "symbol" => "A$"],
            ["code" => "AWG", "name" => "Aruban Florin", "symbol" => "ƒ"],
            ["code" => "AZN", "name" => "Azerbaijani Manat", "symbol" => "₼"],
            ["code" => "BAM", "name" => "Bosnia-Herzegovina Convertible Mark", "symbol" => "KM"],
            ["code" => "BBD", "name" => "Barbadian Dollar", "symbol" => "Bds$"],
            ["code" => "BDT", "name" => "Bangladeshi Taka", "symbol" => "৳"],
            ["code" => "BGN", "name" => "Bulgarian Lev", "symbol" => "лв"],
            ["code" => "BIF", "name" => "Burundian Franc", "symbol" => "FBu"],
            ["code" => "BMD", "name" => "Bermudian Dollar", "symbol" => "$"],
            ["code" => "BND", "name" => "Brunei Dollar", "symbol" => "B$"],
            ["code" => "BOB", "name" => "Bolivian Boliviano", "symbol" => "Bs"],
            ["code" => "BRL", "name" => "Brazilian Real", "symbol" => "R$"],
            ["code" => "BSD", "name" => "Bahamian Dollar", "symbol" => "B$"],
            ["code" => "BWP", "name" => "Botswana Pula", "symbol" => "P"],
            ["code" => "BYN", "name" => "Belarusian Ruble", "symbol" => "Br"],
            ["code" => "BZD", "name" => "Belize Dollar", "symbol" => "BZ$"],
            ["code" => "CAD", "name" => "Canadian Dollar", "symbol" => "C$"],
            ["code" => "CHF", "name" => "Swiss Franc", "symbol" => "CHF"],
            ["code" => "CLP", "name" => "Chilean Peso", "symbol" => "$"],
            ["code" => "CNY", "name" => "Chinese Yuan", "symbol" => "¥"],
            ["code" => "COP", "name" => "Colombian Peso", "symbol" => "$"],
            ["code" => "CRC", "name" => "Costa Rican Colón", "symbol" => "₡"],
            ["code" => "CVE", "name" => "Cape Verdean Escudo", "symbol" => "$"],
            ["code" => "CZK", "name" => "Czech Koruna", "symbol" => "Kč"],
            ["code" => "DJF", "name" => "Djiboutian Franc", "symbol" => "Fdj"],
            ["code" => "DKK", "name" => "Danish Krone", "symbol" => "kr"],
            ["code" => "DOP", "name" => "Dominican Peso", "symbol" => "RD$"],
            ["code" => "DZD", "name" => "Algerian Dinar", "symbol" => "دج"],
            ["code" => "EGP", "name" => "Egyptian Pound", "symbol" => "£"],
            ["code" => "ETB", "name" => "Ethiopian Birr", "symbol" => "Br"],
            ["code" => "EUR", "name" => "Euro", "symbol" => "€"],
            ["code" => "FJD", "name" => "Fijian Dollar", "symbol" => "FJ$"],
            ["code" => "FKP", "name" => "Falkland Islands Pound", "symbol" => "£"],
            ["code" => "GBP", "name" => "British Pound Sterling", "symbol" => "£"],
            ["code" => "GEL", "name" => "Georgian Lari", "symbol" => "₾"],
            ["code" => "GHS", "name" => "Ghanaian Cedi", "symbol" => "₵"],
            ["code" => "GIP", "name" => "Gibraltar Pound", "symbol" => "£"],
            ["code" => "GMD", "name" => "Gambian Dalasi", "symbol" => "D"],
            ["code" => "GNF", "name" => "Guinean Franc", "symbol" => "FG"],
            ["code" => "GTQ", "name" => "Guatemalan Quetzal", "symbol" => "Q"],
            ["code" => "GYD", "name" => "Guyanese Dollar", "symbol" => "GY$"],
            ["code" => "HKD", "name" => "Hong Kong Dollar", "symbol" => "HK$"],
            ["code" => "HNL", "name" => "Honduran Lempira", "symbol" => "L"],
            ["code" => "HRK", "name" => "Croatian Kuna", "symbol" => "kn"],
            ["code" => "HTG", "name" => "Haitian Gourde", "symbol" => "G"],
            ["code" => "HUF", "name" => "Hungarian Forint", "symbol" => "Ft"],
            ["code" => "IDR", "name" => "Indonesian Rupiah", "symbol" => "Rp"],
            ["code" => "ILS", "name" => "Israeli New Shekel", "symbol" => "₪"],
            ["code" => "INR", "name" => "Indian Rupee", "symbol" => "₹"],
            ["code" => "ISK", "name" => "Icelandic Króna", "symbol" => "kr"],
            ["code" => "JMD", "name" => "Jamaican Dollar", "symbol" => "J$"],
            ["code" => "JPY", "name" => "Japanese Yen", "symbol" => "¥"],
            ["code" => "KES", "name" => "Kenyan Shilling", "symbol" => "KSh"],
            ["code" => "KGS", "name" => "Kyrgyzstani Som", "symbol" => "с"],
            ["code" => "KHR", "name" => "Cambodian Riel", "symbol" => "៛"],
            ["code" => "KMF", "name" => "Comorian Franc", "symbol" => "CF"],
            ["code" => "KRW", "name" => "South Korean Won", "symbol" => "₩"],
            ["code" => "KYD", "name" => "Cayman Islands Dollar", "symbol" => "CI$"],
            ["code" => "KZT", "name" => "Kazakhstani Tenge", "symbol" => "₸"],
            ["code" => "LAK", "name" => "Lao Kip", "symbol" => "₭"],
            ["code" => "LBP", "name" => "Lebanese Pound", "symbol" => "ل.ل"],
            ["code" => "LKR", "name" => "Sri Lankan Rupee", "symbol" => "Rs"],
            ["code" => "LRD", "name" => "Liberian Dollar", "symbol" => "L$"],
            ["code" => "LSL", "name" => "Lesotho Loti", "symbol" => "L"],
            ["code" => "LTL", "name" => "Lithuanian Litas", "symbol" => "Lt"],
            ["code" => "MAD", "name" => "Moroccan Dirham", "symbol" => "د.م."],
            ["code" => "MDL", "name" => "Moldovan Leu", "symbol" => "L"],
            ["code" => "MKD", "name" => "Macedonian Denar", "symbol" => "ден"],
            ["code" => "MNT", "name" => "Mongolian Tögrög", "symbol" => "₮"],
            ["code" => "MOP", "name" => "Macanese Pataca", "symbol" => "MOP$"],
            ["code" => "MUR", "name" => "Mauritian Rupee", "symbol" => "₨"],
            ["code" => "MVR", "name" => "Maldivian Rufiyaa", "symbol" => "Rf"],
            ["code" => "MWK", "name" => "Malawian Kwacha", "symbol" => "MK"],
            ["code" => "MXN", "name" => "Mexican Peso", "symbol" => "$"],
            ["code" => "MYR", "name" => "Malaysian Ringgit", "symbol" => "RM"],
            ["code" => "MZN", "name" => "Mozambican Metical", "symbol" => "MT"],
            ["code" => "NAD", "name" => "Namibian Dollar", "symbol" => "N$"],
            ["code" => "NGN", "name" => "Nigerian Naira", "symbol" => "₦"],
            ["code" => "NIO", "name" => "Nicaraguan Córdoba", "symbol" => "C$"],
            ["code" => "NOK", "name" => "Norwegian Krone", "symbol" => "kr"],
            ["code" => "NPR", "name" => "Nepalese Rupee", "symbol" => "₨"],
            ["code" => "NZD", "name" => "New Zealand Dollar", "symbol" => "NZ$"],
            ["code" => "PAB", "name" => "Panamanian Balboa", "symbol" => "B/."],
            ["code" => "PEN", "name" => "Peruvian Sol", "symbol" => "S/."],
            ["code" => "PGK", "name" => "Papua New Guinean Kina", "symbol" => "K"],
            ["code" => "PHP", "name" => "Philippine Peso", "symbol" => "₱"],
            ["code" => "PKR", "name" => "Pakistani Rupee", "symbol" => "₨"],
            ["code" => "PLN", "name" => "Polish Złoty", "symbol" => "zł"],
            ["code" => "PYG", "name" => "Paraguayan Guaraní", "symbol" => "₲"],
            ["code" => "QAR", "name" => "Qatari Riyal", "symbol" => "﷼"],
            ["code" => "RON", "name" => "Romanian Leu", "symbol" => "lei"],
            ["code" => "RSD", "name" => "Serbian Dinar", "symbol" => "din"],
            ["code" => "RUB", "name" => "Russian Ruble", "symbol" => "₽"],
            ["code" => "RWF", "name" => "Rwandan Franc", "symbol" => "FRw"],
            ["code" => "SAR", "name" => "Saudi Riyal", "symbol" => "﷼"],
            ["code" => "SBD", "name" => "Solomon Islands Dollar", "symbol" => "SI$"],
            ["code" => "SCR", "name" => "Seychellois Rupee", "symbol" => "₨"],
            ["code" => "SEK", "name" => "Swedish Krona", "symbol" => "kr"],
            ["code" => "SGD", "name" => "Singapore Dollar", "symbol" => "S$"],
            ["code" => "SHP", "name" => "Saint Helena Pound", "symbol" => "£"],
            ["code" => "SLL", "name" => "Sierra Leonean Leone", "symbol" => "Le"],
            ["code" => "SOS", "name" => "Somali Shilling", "symbol" => "Sh"],
            ["code" => "SRD", "name" => "Surinamese Dollar", "symbol" => "$"],
            ["code" => "STD", "name" => "São Tomé and Príncipe Dobra", "symbol" => "Db"],
            ["code" => "SVC", "name" => "Salvadoran Colón", "symbol" => "₡"],
            ["code" => "SYP", "name" => "Syrian Pound", "symbol" => "£"],
            ["code" => "SZL", "name" => "Swazi Lilangeni", "symbol" => "L"],
            ["code" => "THB", "name" => "Thai Baht", "symbol" => "฿"],
            ["code" => "TJS", "name" => "Tajikistani Somoni", "symbol" => "SM"],
            ["code" => "TOP", "name" => "Tongan Paʻanga", "symbol" => "T$"],
            ["code" => "TRY", "name" => "Turkish Lira", "symbol" => "₺"],
            ["code" => "TTD", "name" => "Trinidad and Tobago Dollar", "symbol" => "TT$"],
            ["code" => "TWD", "name" => "New Taiwan Dollar", "symbol" => "NT$"],
            ["code" => "TZS", "name" => "Tanzanian Shilling", "symbol" => "Sh"],
            ["code" => "UAH", "name" => "Ukrainian Hryvnia", "symbol" => "₴"],
            ["code" => "UGX", "name" => "Ugandan Shilling", "symbol" => "USh"],
            ["code" => "USD", "name" => "United States Dollar", "symbol" => "$"],
            ["code" => "UYU", "name" => "Uruguayan Peso", "symbol" => '$U'],
            ["code" => "UZS", "name" => "Uzbekistani Som", "symbol" => "soʻm"],
            ["code" => "VES", "name" => "Venezuelan Bolívar", "symbol" => "Bs.S"],
            ["code" => "VND", "name" => "Vietnamese Dong", "symbol" => "₫"],
            ["code" => "VUV", "name" => "Vanuatu Vatu", "symbol" => "VT"],
            ["code" => "WST", "name" => "Samoan Tālā", "symbol" => "WS$"],
            ["code" => "XAF", "name" => "Central African CFA Franc", "symbol" => "FCFA"],
            ["code" => "XCD", "name" => "East Caribbean Dollar", "symbol" => "EC$"],
            ["code" => "XOF", "name" => "West African CFA Franc", "symbol" => "CFA"],
            ["code" => "XPF", "name" => "CFP Franc", "symbol" => "₣"],
            ["code" => "YER", "name" => "Yemeni Rial", "symbol" => "﷼"],
            ["code" => "ZAR", "name" => "South African Rand", "symbol" => "R"],
            ["code" => "ZMK", "name" => "Zambian Kwacha (pre-2013)", "symbol" => "ZK"],
            ["code" => "ZWD", "name" => "Zimbabwean Dollar (1980–2009)", "symbol" => "Z$"],
        ];

        DB::table("currencies")->insert($currencies);
    }
}
